var weapons =
["landmine",
"bow",
"melee",
"paintball",
"mason jar",
"cocaine bear",
"fidget spinner",
"assault rifle",
"frisbee",
"tank"];

var melee =
["sword",
"knife",
"golf club",
"baseball bat",
"massive cock",
"potato",
"shoe",
"lightsaber",
"weighted dinosaur",
"diamond sword",
"dual swords",
"TI-Nspire",
"folding chair",
"steam controller",
"TBD",
"war axe",
"greatsword",
"Victorian broadsword",
"shortsword",
"mace",
"bottle of vodka"];

var itemsToFind =
["Mink clan merch",
"poisonous fruit tree",
"sprite cranberry",
"Erics dab pen",
"Morbius DVD",
"groan tube",
"wild Ohio Fried Chicken",
"glasses that cure color-blindness",
"bleach gummy bottle",
"paintball",
"used Band-Aid",
"TBD",
"pack of condoms",
"tent",
"biology textbook",
"bucket of KFC",
"tin of Donald Trump's bronzer",
"Emoji Movie on laserdisc",
"Julians toes",
"quenched and tempered steel",
"VIP ticket to Tana Mojo concert",
"unicorn",
"spiritual enlightenment in a Villanova brochure",
"TBD",
"diamond pickaxe",
"Stalin mustache",
"bone-hurting juice",
"one spaghetti",
"50% off coupon to an SAT prep class",
"indescribable object",
"chocolate-covered cotton",
"stick of Old Spice deodorant",
"freeze ray",
"findings
"Kirby"];

var itemsThatGivePoints = [
"Erics dab pen",
"sprite cranberry",
"glasses that cure color-blindness",
"Julians toes",
"stick of Old Spice deodorant",
"50% off coupon to an SAT prep class"];

var causeAndEffect =
["TBD",
"TBD",
"poisonous fruit tree",
"eats a poisonous fruit",
"sprite cranberry",
"drinks a sprite cranberry and turns into Lebron James",
"Erics dab pen",
"takes a ripski",
"groan tube",
"goes OOOOOOUUUUULLE",
"tbd",
"tbd",
"wild Ohio Fried Chicken",
"random chicken",
"glasses that cure color-blindness",
"is no longer color-blind",
"bleach gummy bottle",
"eats bleach gummy bottle",
"used Band-Aid",
"random bandaid",
"pack of condoms",
"safe dating",
"tent",
"constructs a tent",
"biology textbook",
"reads a biology textbook and falls asleep",
"bucket of KFC",
"eats KFC",
"tin of Donald Trump's bronzer",
"becomes as orange as Donald Trump and dies of chemical poisoning",
"Emoji Movie on laserdisc",
"dies of pure cancer after watching the Emoji Movie",
"Julians toes",
"develops a foot fetish",
"quenched and tempered steel",
"constructs a geometrically stable truss",
"VIP ticket to Tana Mojo concert",
"gets assaulted by a toothbrush at Tana Mojo concert",
"unicorn",
"pets the pink fluffy unicorn",
"spiritual enlightenment in a Villanova brochure",
"sees the light and adheres to the all-boy advantage",
"Agrawal star",
"jealousy",
"diamond pickaxe",
"mines diamond ore",
"bone-hurting juice",
"has major bone pain after drinking bone-hurting juice",
"Stalin mustache",
"gulag",
"one spaghetti",
"eats a singular spaghetti",
"50% off coupon to an SAT prep class",
"attends an SAT class for half the price",
"indescribable object",
"object",
"chocolate-covered cotton",
"gets indigestion from too much Egyptian cotton",
"stick of Old Spice deodorant",
"smells good, but it\'s Old Spice, not your boy\'s cologne",
"freeze ray",
"freezes",
"email",
"dies of shame after being kicked off the finance team",
"findings",
"becomes the most successful paleontologist from Vatican City"];

var killCauseAndEffect =
["landmine",
"random mine",
"bow",
"shoots",
"cocaine bear",
"'s cocaine bear mauls",
"paintball",
"brings one less paintball, so",
"mason jar",
"gets put in the jar",
"melee",
"kills",
"fidget spinner",
"spins fidget spinner fatally at",
"assault rifle",
"shoots",
"frisbee",
"decapitates",
"tank",
"murders"];

var shelter =
["cave",
"tree",
"dodgeball room",
"geometrically stable truss",
"podcast room",
"horse carcass",
"igloo",
"Olive Garden",
"couch",
"sleeping bag",
"Jacobs room",
"brothel"];

var cornucopia =
["run",
"supply",
"weapon",
"battle"];

var sponsor =
["empty box",
"paintball",
"used Band-Aid",
"sprite cranberry",
"pack of condoms",
"steak and a blowjob",
"biology textbook",
"bucket of KFC",
"tin of Donald Trump's bronzer",
"Morbius DVD",
"Julians toes",
"groan tube",
"VIP ticket to Tana Mojo concert",
"Agrawal star",
"Leo",
"diamond pickaxe",
"Stalin mustache",
"bone-hurting juice",
"one spaghetti",
"50% off coupon to an SAT prep class",
"indescribable object",
"chocolate-covered cotton",
"stick of Old Spice deodorant",
"freeze ray"];

var misc =
["wanders around",
"picks flowers",
"talks to",
"drops a rant against",
"levels up",
"sings us a song",
"is the sheriff",
"puts milk in the cabinet",
"goes on a wawa run",
"loses the game",
"cries",
"has nightmares",
"requires coochie",
"sells feet pics",
"does a haha funni",
"experiences post-nut clarity",
"gets doxxed by keemstar",
"starts an only fans",
"gets hit with rizz",
"gets cheeks clapped",
"attaches a measuring tape to a toaster",
"gains Disney Channel flo",
"TBD",
"blames Nelson",
"has the braincell",
"has a live Julian reaction",
"is crazy? I was crazy once, they put me in a room, a rubber room...",
"catches in the rye",
"raises the mission requirement to 65",
"tries to post a Vine",
"gets pissed on by Shadow the Hedgehog",
"changes genders",
"could stop at five or six store, or just one",
"yells \"NikhilYA!\"",
"finds Pepe",
"finds Chuck Norris",
"puts chemicals in the water to turn the frogs gay",
"fights the Ender dragon",
"gets married to",
"joins the Society of Teen Suicide Prevention",
"finds Bishan Agrawal",
"barrel rolls",
"finds Dory",
"finds Nemo"];

var injury =
["gets a cold",
"gets the flu",
"gets mono and strep throat",
"gets strep throat",
"becomes lactose intolerant",
"is stung by BEES",
"battles and wounds",
"has no bitches, or maidens, and becomes depressed",
"goes deaf due to rock n roll McDonalds",
"triggered",
"gets carpal tunnel syndrome from playing osu",
"gets osteoporosis",
"gets crippling depression",
"tries to break the fourth wall",
"gets caught in 4k by",
"sees things twice",
"sees things once",
"reads a disheartening message in Comic Sans",
"slips and slides on a banana peel",
"gets Hodgkin\'s Lymphoma",
"gets a bladder infection",
"get called out at Honest Hour",
"gets devastating hiccups",
"gets yellow fever",
"gets forced into BEES",
"TBD",
"unluckily trips despite the 1/100 chance",
"gets put in the mason jar",
"develops stage 4 brain cancer after watching Morbius DVD",
"gets necrosis",
"gets forced into fall mentorship"];

var injEffect =
["shoots",
"injures",
"mason jar",
"gets put in the jar",
"paintball",
"gets hit by a paintball shot by",
"basketball",
"gets juked by",
"octobrush",
"wounds",
"fidget spinner",
"spins fidget spinner nonfatally at",
"assault rifle",
"shoots and grazes"];

var variousDeaths =
["strangles",
"chokes on",
"eats cheese while lactose intolerant",
"gets pegged by",
"has no bitches, or maidens, and becomes depressed",
"gets burned to death from",
"hangs",
"decides to take a permanent nap",
"falls off a cliff while playing Pokemon Go",
"yells \"woag wiag wiag\" at",
"gets caught in 4k by",
"chokes on crabapples in cheeks",
"forgets how to breathe",
"uses dank memes to kill",
"navy seals",
"unsafe dating",
"gaslit, gatekept, girlbossed",
"gets pegged by",
"loses circulation looking too good in that maid costume",
"loses circulation looking too tight in that maid costume",
"fell into the void",
"was slain by a zombie pigman",
"withered away",
"says the n word",
"fatally roundhouse kicks",
"got rule 34rd",
"L + Ratios",
"curses on a Christian server and gets smote",
"spontaneously combusts",
"gets nae naed by",
"hate crimes",
"realizes we live in a society",
"dies in the Matrix",
"succumbs to lethal peer pressure from",
"can't have shit in detroit, not even their life"];

var doubleDeath =
["strangles"
"gaslit, gatekept, girlbossed",
"gets nae naed by",
"gets memed on by"
"chokes on",
"gets pegged by",
"hate crimes"
"gets caught in 4k by"
"L + ratios"];

var options =
["weapons",
"items",
"use",
"shelter",
"use",
"misc",
"injury",
"use",
"death",
"heal",
"items",
"use",
"injury",
"use"];

var vowels = ["a","e","i","o","u"];

